### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nicolsondsouza** [meteor/miniredis#2]
1. How can I connect to remote redis, with this package
2. HSET function has 3 parameters "key field value",  but in the package it's only 2

**Comment by Slava** [comment]
See https://github.com/meteor/redis-livedata

**Comment by nicolsondsouza** [comment]
Hi Slava, 

I checked that first, but it is for collection use not for redis-cli commands
var redis = new Miniredis.Hash;
Does provides me with cli support, but not sure how to sync them with remote server,
nor there is any documentation here.

I have to use 
https://github.com/mranney/node_redis
If this package doesn't work.

**Comment by Slava** [comment]
I don't understand what do you mean? The linked package has nothing to do with Redis CLI, in fact, it connects directly to a running Redis server over the connection string (using the binary node redis driver internally).

**Comment by nicolsondsouza** [comment]
client = redis.createClient(6379,"0.0.0.0");
client.hset("mapName", "key", "value", function(err,result){
    console.log(err,result);
});

This does the work for me,
I am assuming the same thing to be in Miniredis package

var redis = new Miniredis.Hash;
redis.hset("mapName", "key", "value");

**Comment by Slava** [comment]
@nicolsondsouza did you read the README.md file by the link I posted above? Please go and read.

**Comment by nicolsondsouza** [comment]
ok
